StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65AA7B18416B086C}" {
   Id "AR-RKN_SP01M-Action_Ack"
   Target_en_us "Acknowledge"
   Modified 1705687053
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B18596686D0}" {
   Id "AR-RKN_SP01M-Action_TakeHECrate"
   Target_en_us "Take HE Crate"
   Modified 1706118266
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B182CE9F35D}" {
   Id "AR-RKN_SP01M-Action_TakeShell"
   Target_en_us "Take Shell"
   Modified 1705686977
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C381E4405B}" {
   Id "AR-RKN_SP01M-Action_TakeSmokeCrate"
   Target_en_us "Take Smoke Crate"
   Modified 1706118294
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946438C29D709E}" {
   Id "AR-RKN_SP01M-Brief_CallForFire_Text"
   Target_en_us "When requested a firemission, the requester will first provide the target location. This can be in the form of "\
   " - Grid: Corrdinates as refereced on your map"\
   " - Polar: Bearing from requester's position. Requires knowing the requester's position."\
   " - Shift from known point: Some distance away from a named location on your map."\
   ""\
   "Another piece of info is whether the requester want you to strike the target with effect (5 shells) right away, called \"Fire for effect\", or act as observer and guide you unto target. This is called \"Adjust fire\". "\
   "  Additional information may also be given including shell type, and recommended impact trajectory angle (based on surrounding terrain)."\
   ""\
   "<b>Adjust fire</b>"\
   "During adjustment phase, the observer will expect one shell at a time. Upon impact the observer will give corrections. These correction are usually based on the observer's reference."\
   ""\
   "Examples "\
   " - \"Drop 300 meters, left 50 meters\": target 300 meters closer to the observer, and 50 meters to his left."\
   " - \"Add 100 meters\": target 100 meters further away from the observer."\
   ""\
   "Though keep an ear to how the observer gives the correction, since NATO is stretched thin and correct procedures may not have been trained."\
   "  In case the initial target location info did not yield the position of the observer, and adjustments are called in a polar manner, then the adjustments will be preceded by the bearing from observer to target."\
   "  Once a shell has found the target during adjustment, the observer will call \"Fire for effect\", after which 5 shells are expected with no further adjustments."
   Modified 1706117584
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946438CA04E7E5}" {
   Id "AR-RKN_SP01M-Brief_CallForFire_Title"
   Target_en_us "Call for Fire"
   Modified 1706117588
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65944AE7FE18FA05}" {
   Id "AR-RKN_SP01M-Brief_Mission"
   Target_en_us "You crew a mortar and has been stationed on a hill outpost. The outpost is not yet finished, and your officer is on his way from the nearby camp with the shell ammunition."
   Modified 1704224080
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946439330138CB}" {
   Id "AR-RKN_SP01M-Brief_Situation"
   Target_en_us "The Cold War has gone lukewarm. Proxy wars has slowly turned into small scale direct conflict between the nuclear powers in remote third-world countries."\
   "The island of Everon is eyed by the USSR, and its Government has invited a small US force to build a camp there to encourage the soviet's better judgement. "\
   "Though the token force is small, as there is little interest in pulling from more important fronts to this ocean rock."
   Modified 1704224275
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B1950669760}" {
   Id "AR-RKN_SP01M-End_Bad_Desc"
   Target_en_us "Your response to enemy infiltrators was ineffective. NATO forces have lost too many assets for an effective response."
   Modified 1705686569
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B195894A6C6}" {
   Id "AR-RKN_SP01M-End_Bad_Subtitle"
   Target_en_us "NATO forces in jeopardy"
   Modified 1705686552
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B1979618580}" {
   Id "AR-RKN_SP01M-End_Desertion_Desc"
   Target_en_us "Your mortar remains the best asset NATO forces on the island has available. Without it your comrades will fall to enemy infiltrators."
   Modified 1705686610
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B19416A787D}" {
   Id "AR-RKN_SP01M-End_Desertion_Subtitle"
   Target_en_us "Desertion will not be tolerated"
   Modified 1705686596
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B193388082D}" {
   Id "AR-RKN_SP01M-End_Good_Desc"
   Target_en_us "Your effective response to the enemy infiltrators has disrupted USSR invasion plans. NATO forces remain in complete control of Everon."
   Modified 1705686514
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B19373DD0FA}" {
   Id "AR-RKN_SP01M-End_Good_Subtitle"
   Target_en_us "NATO forces sieze the day"
   Modified 1705686504
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B1888212298}" {
   Id "AR-RKN_SP01M-End_MortarDestroyed_Desc"
   Target_en_us "Without the mortar you will be unable to support your allies."
   Modified 1705686900
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B1892A49C3A}" {
   Id "AR-RKN_SP01M-End_MortarDestroyed_Subtitle"
   Target_en_us "Mortar destroyed"
   Modified 1705686685
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B196A27F60F}" {
   Id "AR-RKN_SP01M-End_Murder_Desc"
   Target_en_us "WTF man?!"
   Modified 1705686665
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B196F23C17D}" {
   Id "AR-RKN_SP01M-End_Murder_Subtitle"
   Target_en_us "Traitors will not be tolerated"
   Modified 1705686637
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B19DD8A491A}" {
   Id "AR-RKN_SP01M-End_Neutral_Desc"
   Target_en_us "Your response to enemy infiltrators was lacking. NATO forces must consolidate to respond to the threat."
   Modified 1705686313
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AA7B19BE636776}" {
   Id "AR-RKN_SP01M-End_Neutral_Subtitle"
   Target_en_us "NATO forces pushed back"
   Modified 1705686287
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C17D9555AF}" {
   Id "AR-RKN_SP01M-Hint_Ack_Text"
   Target_en_us "Find and interact with the radio to acknowledge."
   Modified 1706120206
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C0FC390AFF}" {
   Id "AR-RKN_SP01M-Hint_Ack_Title"
   Target_en_us "Someone is calling you"
   Modified 1706117954
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C12042F3BE}" {
   Id "AR-RKN_SP01M-Hint_CallForFire_Text"
   Target_en_us "Read the journal entry on your map to learn about the Call for Fire protocol."
   Modified 1706117699
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C124F77449}" {
   Id "AR-RKN_SP01M-Hint_CallForFire_Title"
   Target_en_us "Call for Fire"
   Modified 1706117648
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C4AA086E86}" {
   Id "AR-RKN_SP01M-Hint_Stand_Text"
   Target_en_us "Stand up"
   Modified 1706119961
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65B148C4B7379E98}" {
   Id "AR-RKN_SP01M-Hint_Stand_Title"
   Target_en_us "No sleeping on the job"
   Modified 1706119950
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19FF84BF0A}" {
   Id "AR-RKN_SP01M-Task_FM0_Desc"
   Target_en_us "A nearby checkpoint is under attack. Spot the attackers and send some shells their way before it is too late."
   Modified 1705701728
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19C7E8CEC6}" {
   Id "AR-RKN_SP01M-Task_FM0_Title"
   Target_en_us "Assist checkpoint guards"
   Modified 1705701716
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19EAEB8D32}" {
   Id "AR-RKN_SP01M-Task_FM1A_Desc"
   Target_en_us "Charlie 2-2 is taking cover in a large building near Pennants Pass. They request an adjust fire mission 100M to their 310 bearing."
   Modified 1705701769
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19EE89C270}" {
   Id "AR-RKN_SP01M-Task_FM1A_Title"
   Target_en_us "Charlie 2-2 Fire Mission"
   Modified 1705701761
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1916295271}" {
   Id "AR-RKN_SP01M-Task_FM1B_Desc"
   Target_en_us "Alpha 2-2 is taking cover in a building complex called Camurac. They request an adjust fire mission 200M to their 065 bearing."
   Modified 1705701802
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19181472E9}" {
   Id "AR-RKN_SP01M-Task_FM1B_Title"
   Target_en_us "Charlie 2-2 Fire Mission"
   Modified 1705701792
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC190132F7FF}" {
   Id "AR-RKN_SP01M-Task_FM1C_Desc"
   Target_en_us "Charlie 1 is requesting an adjust fire mission on grid 071 028"
   Modified 1705701836
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19087BF0FA}" {
   Id "AR-RKN_SP01M-Task_FM1C_Title"
   Target_en_us "Charlie 2 Fire Mission"
   Modified 1705701819
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC192FAB107B}" {
   Id "AR-RKN_SP01M-Task_FM2A_Desc"
   Target_en_us "Alpha actual is requesting fire for effect, 300 meters south of center of Camp Pertrude."
   Modified 1705701871
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1936044F10}" {
   Id "AR-RKN_SP01M-Task_FM2A_Title"
   Target_en_us "Alpha actual FIre mission"
   Modified 1705701860
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC195908BFF1}" {
   Id "AR-RKN_SP01M-Task_FM2B_Desc"
   Target_en_us "Alpha actual is requesting adjust fire mission, 200 meters north and 200 meters east of center of Camp Pertrude."
   Modified 1705701906
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1921ADEA01}" {
   Id "AR-RKN_SP01M-Task_FM2B_Title"
   Target_en_us "Alpha actual FIre mission"
   Modified 1705701893
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC194E18B878}" {
   Id "AR-RKN_SP01M-Task_FM2C_Desc"
   Target_en_us "Alpha actual is requesting fire for effect, 300 meters south and 250 meters east of center of Camp Pertrude."
   Modified 1705701931
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1950BEE5D9}" {
   Id "AR-RKN_SP01M-Task_FM2C_Title"
   Target_en_us "Alpha actual FIre mission"
   Modified 1705701920
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC197465DC12}" {
   Id "AR-RKN_SP01M-Task_FM3A_Desc"
   Target_en_us "Requests adjust fire mission at grid 092 015"
   Modified 1705701973
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC197E9E4456}" {
   Id "AR-RKN_SP01M-Task_FM3A_Title"
   Target_en_us "India 3 Fire mission"
   Modified 1705701961
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1967E6FC8E}" {
   Id "AR-RKN_SP01M-Task_FM3B_Desc"
   Target_en_us "Bravo 2 requests fire for effect on the road near Cheval Gin Lodge"
   Modified 1705702001
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC196883DA9F}" {
   Id "AR-RKN_SP01M-Task_FM3B_Title"
   Target_en_us "Bravo 2 Fire mission"
   Modified 1705701991
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC1894419432}" {
   Id "AR-RKN_SP01M-Task_FM3C_Desc"
   Target_en_us "Bravo 2 requests adjust fire mission on a building north-west of Oar ridge"
   Modified 1705702029
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC189EE3EA77}" {
   Id "AR-RKN_SP01M-Task_FM3C_Title"
   Target_en_us "Bravo 2 Fire mission"
   Modified 1705702019
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19DD7445E2}" {
   Id "AR-RKN_SP01M-Task_Mortar_Desc"
   Target_en_us "Locate the enemy mortar, and detroy it with counter-fire."
   Modified 1705701669
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65AAEC19B0B31447}" {
   Id "AR-RKN_SP01M-Task_Mortar_Title"
   Target_en_us "Counter the enemy mortar"
   Modified 1705701638
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467C6262585}" {
   Id "AR-RKN_SP01M-VA_Ending_Bad2"
   Target_en_us "The situation has become untenable. Enemy ground forces are approaching your position."
   Modified 1704269849
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467C27BAD0E}" {
   Id "AR-RKN_SP01M-VA_Ending_Bad3"
   Target_en_us "Sabotage the tube and make your way to Camp Protrude."
   Modified 1704269856
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467F9AB2C9D}" {
   Id "AR-RKN_SP01M-VA_Ending_Bad4"
   Target_en_us "I'm afraid you're on your own until you get here. HQ out."
   Modified 1704269864
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467D1D60724}" {
   Id "AR-RKN_SP01M-VA_Ending_Good2"
   Target_en_us "Excellent work with those fire missions. Assistance is on the way. HQ out."
   Modified 1704269819
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467CC7BB6DF}" {
   Id "AR-RKN_SP01M-VA_Ending_Neutral2"
   Target_en_us "We've lost too many assets in the southern half. Your position is under threat."
   Modified 1704269833
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946467C81132F2}" {
   Id "AR-RKN_SP01M-VA_Ending_Neutral3"
   Target_en_us "We're sending a team to you for relocation further north. HQ out."
   Modified 1704269839
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D79293EE9}" {
   Id "AR-RKN_SP01M-VA_EnemyMortar_Inquery1"
   Target_en_us "Hammer, this is India 3-2 come in?"
   Modified 1704273100
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D74B0874B}" {
   Id "AR-RKN_SP01M-VA_EnemyMortar_Inquery2"
   Target_en_us "We think we saw some dust rising on that ridge on the opposite side of the valley from your outpost."
   Modified 1704273107
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D70F8E301}" {
   Id "AR-RKN_SP01M-VA_EnemyMortar_Inquery3"
   Target_en_us "We thought perhaps you could check it out with your binoculars?"
   Modified 1704273115
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D6FEAFD6F}" {
   Id "AR-RKN_SP01M-VA_EnemyMortar_Inquery4"
   Target_en_us "India 3-2 to Hammer, was that an explosion?"
   Modified 1704273129
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C9F8F3CB9}" {
   Id "AR-RKN_SP01M-VA_FM0_Request1"
   Target_en_us "India 3-2 to Hammer! We're taking fire and need assistance!"
   Modified 1704273153
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C9BC61868}" {
   Id "AR-RKN_SP01M-VA_FM0_Request2"
   Target_en_us "We're suppressed and can't see the exact location of the hostiles. Somewhere to our <i>south-west</i>!"
   Modified 1704394780
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C969E996A}" {
   Id "AR-RKN_SP01M-VA_FM0_Request3"
   Target_en_us "Maybe you can see them from there. Please hurry, we're in a bad position. Out."
   Modified 1704273168
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C81FFD9EA}" {
   Id "AR-RKN_SP01M-VA_FM0_Success1"
   Target_en_us "I can't hear the shooting anymore. I think you saved our skin there Hammer. Out."
   Modified 1704273199
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645CB995A365}" {
   Id "AR-RKN_SP01M-VA_FM0_Success_Smoke1"
   Target_en_us "Hammer. India 3-2. We've evacuated thanks to the smoke."
   Modified 1704273211
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645CB5A91E27}" {
   Id "AR-RKN_SP01M-VA_FM0_Success_Smoke2"
   Target_en_us "I can't thank you enough. Out."
   Modified 1704273221
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C8F13BD1E}" {
   Id "AR-RKN_SP01M-VA_FM0_Timeout1"
   Target_en_us "This is India 3-2 again. They ran back into the woods. You can save your ammo aswell."
   Modified 1704535408
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645C8B6A61DA}" {
   Id "AR-RKN_SP01M-VA_FM0_Timeout2"
   Target_en_us "Though they got us good. Nicked me, and I don't hear the others. HQ is sending help. India 3-2 out."
   Modified 1704535417
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464565F3B1E1E}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Hit"
   Target_en_us "Charlie 2-2. You got it! <i>Fire for effect</i>. Out."
   Modified 1704394828
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946449A1A2F337}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Left"
   Target_en_us "Right"
   Modified 1704278552
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645657ABAD94}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Over"
   Target_en_us "Drop"
   Modified 1704278352
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464562ACF8CC8}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Prefix"
   Target_en_us "Charlie 2-2. Splash."
   Modified 1704394841
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946449A2B2C93D}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Right"
   Target_en_us "Left"
   Modified 1704278557
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645652B5E29C}" {
   Id "AR-RKN_SP01M-VA_FM1A_Adj_Short"
   Target_en_us "Add"
   Modified 1704278358
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433F1B926D9}" {
   Id "AR-RKN_SP01M-VA_FM1A_FriendlyFire1"
   Target_en_us "Hammer this is Charlie 2-2! Cease fire, you're hitting us!"
   Modified 1704269672
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464306465C4A5}" {
   Id "AR-RKN_SP01M-VA_FM1A_Miss1"
   Target_en_us "This is Charlie 2-2. Little effect on target."
   Modified 1704269684
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946430629A298C}" {
   Id "AR-RKN_SP01M-VA_FM1A_Miss2"
   Target_en_us "We're going to attempt to break out before it's too late. Wish us luck. Charlie out"
   Modified 1704269687
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464305C2E7329}" {
   Id "AR-RKN_SP01M-VA_FM1A_Request1"
   Target_en_us "Hammer, this is Charlie 2-2!"
   Modified 1704269691
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594643050118493}" {
   Id "AR-RKN_SP01M-VA_FM1A_Request2"
   Target_en_us "We got ambushed on our way to Durras through <i>Pennants Pass</i>."
   Modified 1704394869
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464304F5133BC}" {
   Id "AR-RKN_SP01M-VA_FM1A_Request3"
   Target_en_us "We managed to take cover in a <i>large lone building</i>, but we'll need fire support to slip away."
   Modified 1704394880
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594643046D61439}" {
   Id "AR-RKN_SP01M-VA_FM1A_Request4"
   Target_en_us "<i>Adjust fire mission. At our 310 bearing, 100 meters. HE. Very high angle.</i> Danger close. Out."
   Modified 1704394182
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433971981A6}" {
   Id "AR-RKN_SP01M-VA_FM1A_Success1"
   Target_en_us "Hammer, Charlie 2-2"
   Modified 1704228659
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594643393ED3D6F}" {
   Id "AR-RKN_SP01M-VA_FM1A_Success2"
   Target_en_us "Good effect. We broke out while they were scattered."
   Modified 1704228666
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464338FEA029A}" {
   Id "AR-RKN_SP01M-VA_FM1A_Success3"
   Target_en_us "We'll take the long around back to Regina and link up with the rest of Charlie."
   Modified 1704228677
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464338BADD495}" {
   Id "AR-RKN_SP01M-VA_FM1A_Success4"
   Target_en_us "End of mission. Out."
   Modified 1704228683
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594643076180C96}" {
   Id "AR-RKN_SP01M-VA_FM1A_Timeout1"
   Target_en_us "This is Charlie 2-2. We're being surrounded and cannot wait any longer."
   Modified 1704228603
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464306CDE38F0}" {
   Id "AR-RKN_SP01M-VA_FM1A_Timeout2"
   Target_en_us "We're going to attempt to break out before it's too late. Wish us luck. Charlie out."
   Modified 1704228616
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433DEF30E00}" {
   Id "AR-RKN_SP01M-VA_FM1B_Miss1"
   Target_en_us "This is Charlie 2-2. You missed, but it at least spooked them some."
   Modified 1704228763
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464529A24E96D}" {
   Id "AR-RKN_SP01M-VA_FM1B_Request2"
   Target_en_us "We got ambushed on our way to Regina."
   Modified 1704276168
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433BA6DECFA}" {
   Id "AR-RKN_SP01M-VA_FM1B_Request3"
   Target_en_us "We're taking cover in a building complex we believe is called <i>Camurac</i>. I say again, Camurac."
   Modified 1704394937
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433B7BF5504}" {
   Id "AR-RKN_SP01M-VA_FM1B_Request4"
   Target_en_us "We need a Fire mission. <i>Adjust fire. Polar. Bearing 065, distance 200 meters.</i> HE. Danger close. Out."
   Modified 1704394202
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433C50B651A}" {
   Id "AR-RKN_SP01M-VA_FM1B_Success1"
   Target_en_us "Hammer, good effect on target! 3 enemy casualties. The rest are scattering."
   Modified 1704228802
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433A116E017}" {
   Id "AR-RKN_SP01M-VA_FM1B_Timeout1"
   Target_en_us "This is Charlie 2-2 we need immediate assistance! They're about to-- *static*"
   Modified 1704228751
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448FC3F42AC}" {
   Id "AR-RKN_SP01M-VA_FM1C_Adj_Hit"
   Target_en_us "Charlie 1-2. <i>Fire for effect</i>. Out."
   Modified 1704394325
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448C6DFE743}" {
   Id "AR-RKN_SP01M-VA_FM1C_Adj_Prefix"
   Target_en_us "Charlie 1-2. Splash. <i>Direction 007</i>."
   Modified 1704394217
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594643311DB2C39}" {
   Id "AR-RKN_SP01M-VA_FM1C_Miss1"
   Target_en_us "Hammer, Charlie 1. No effective on target."
   Modified 1704228893
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433E80AB01B}" {
   Id "AR-RKN_SP01M-VA_FM1C_Request1"
   Target_en_us "Hammer, this is Charlie 1."
   Modified 1704228851
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433E4F7B2A3}" {
   Id "AR-RKN_SP01M-VA_FM1C_Request2"
   Target_en_us "<i>Adjust fire. Grid 071 028.</i>"
   Modified 1704394229
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946433E17F63CD}" {
   Id "AR-RKN_SP01M-VA_FM1C_Request3"
   Target_en_us "Hostile sniper team in the tree line. Likely ambush. HE. Out."
   Modified 1704228867
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464330E12E106}" {
   Id "AR-RKN_SP01M-VA_FM1C_Success1"
   Target_en_us "Hammer, Charlie 1. Good effective on target."
   Modified 1704228905
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464330B7D8C1C}" {
   Id "AR-RKN_SP01M-VA_FM1C_Success2"
   Target_en_us "Enemy team destroyed. End of mission. Out."
   Modified 1704228910
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464331B5266EA}" {
   Id "AR-RKN_SP01M-VA_FM1C_Timeout2"
   Target_en_us "Bird has flown. End of mission. Out."
   Modified 1704228883
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464D8F176CC}" {
   Id "AR-RKN_SP01M-VA_FM2A_FriendlyFire1"
   Target_en_us "Hammer! Friendly fire! End of mission. Out!"
   Modified 1704269351
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464B64E4FFA}" {
   Id "AR-RKN_SP01M-VA_FM2A_Miss2"
   Target_en_us "Little to no effect on target. End of mission. Out."
   Modified 1704269318
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594646560097E9A}" {
   Id "AR-RKN_SP01M-VA_FM2A_Request1"
   Target_en_us "Hammer, this is Alpha actual."
   Modified 1704269222
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464649CC96286}" {
   Id "AR-RKN_SP01M-VA_FM2A_Request2"
   Target_en_us "Fire mission. <i>Shift from known point. Camp Protrude, 300 meters south.</i>"
   Modified 1704394252
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464649BE50FC9}" {
   Id "AR-RKN_SP01M-VA_FM2A_Request3"
   Target_en_us "<i>Fire for effect</i>. Hostile infantry in the open. HE. out."
   Modified 1704394387
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464D09AC13B}" {
   Id "AR-RKN_SP01M-VA_FM2A_Success2"
   Target_en_us "Good effect on target. End of mission. Out."
   Modified 1704269366
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464A1253F90}" {
   Id "AR-RKN_SP01M-VA_FM2A_Timeout2"
   Target_en_us "Cancel firemission. Situation has evolved. Out."
   Modified 1704269336
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464480E30418B}" {
   Id "AR-RKN_SP01M-VA_FM2B_Adj_Hit"
   Target_en_us "Alpha actual. <i>Fire for effect</i>. Out."
   Modified 1704394299
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448062D554B}" {
   Id "AR-RKN_SP01M-VA_FM2B_Adj_Prefix"
   Target_en_us "Alpha actual. Splash. <i>Direction 315.</i>"
   Modified 1704394262
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464CBC0B058}" {
   Id "AR-RKN_SP01M-VA_FM2B_Request2"
   Target_en_us "Need <i>adjust fire mission, shift from known point. Camp Protrude, 200 meters north, 200 east.</i>"
   Modified 1704394270
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464C08E894B}" {
   Id "AR-RKN_SP01M-VA_FM2B_Request3"
   Target_en_us "Hostile encampment. Requesting HE. out."
   Modified 1704269395
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464F2DA993E}" {
   Id "AR-RKN_SP01M-VA_FM2C_Request2"
   Target_en_us "Fire mission. <i>Shift from known point. Camp Protrude, 300 meters south, 250 east.</i>"
   Modified 1704394279
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448299B041B}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Hit"
   Target_en_us "India 3. On Target. <i>Fire for effect</i>! Out."
   Modified 1704888465
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448487256D4}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Left"
   Target_en_us "East"
   Modified 1704279283
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464482081AD68}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Over"
   Target_en_us "South"
   Modified 1704279241
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644830053484}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Prefix"
   Target_en_us "India 3. Splash. Adjust"
   Modified 1704888460
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644844BCEB3D}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Right"
   Target_en_us "West"
   Modified 1704279288
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464485C566C7A}" {
   Id "AR-RKN_SP01M-VA_FM3A_Adj_Short"
   Target_en_us "North"
   Modified 1704279250
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594646411D25654}" {
   Id "AR-RKN_SP01M-VA_FM3A_Miss2"
   Target_en_us "Splash ineffective. Call off mission. We'll reevaluate our options. Out."
   Modified 1704269477
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464E542728E}" {
   Id "AR-RKN_SP01M-VA_FM3A_Request1"
   Target_en_us "India 3 to Hammer"
   Modified 1704269445
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464E0AAA557}" {
   Id "AR-RKN_SP01M-VA_FM3A_Request2"
   Target_en_us "Requesting <i>adjust fire, grid 092 015</i>"
   Modified 1704394406
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464641CAB0931}" {
   Id "AR-RKN_SP01M-VA_FM3A_Request3"
   Target_en_us "Some hostiles held up in a building. Need help flushing them out. Out."
   Modified 1704269459
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464640C2AF384}" {
   Id "AR-RKN_SP01M-VA_FM3A_Success2"
   Target_en_us "Good splashes. We see signs of surrender. End of mission. Out."
   Modified 1704269487
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464641B55DA3D}" {
   Id "AR-RKN_SP01M-VA_FM3A_Timeout2"
   Target_en_us "We can't wait forever for firesupport. Call off mission. We'll reevaluate our options. Out."
   Modified 1704269467
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464642D8F6A23}" {
   Id "AR-RKN_SP01M-VA_FM3B_Miss2"
   Target_en_us "Little effect on target. End of mission, they're scattering. Out."
   Modified 1704269541
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464640450260A}" {
   Id "AR-RKN_SP01M-VA_FM3B_Request1"
   Target_en_us "Bravo to Hammer. Come in!"
   Modified 1704269504
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594646403029797}" {
   Id "AR-RKN_SP01M-VA_FM3B_Request2"
   Target_en_us "Concentration of enemy infiltrators on the road next to <i>Cheval Gin Lodge</i>."
   Modified 1704395098
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464643F195A08}" {
   Id "AR-RKN_SP01M-VA_FM3B_Request3"
   Target_en_us "Need immediate <i>fire for effect</i>. Out."
   Modified 1704395120
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464642B804524}" {
   Id "AR-RKN_SP01M-VA_FM3B_Success2"
   Target_en_us "Good hits! Wrecked those bastards! End of mission. Out."
   Modified 1704269551
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464643AAEA764}" {
   Id "AR-RKN_SP01M-VA_FM3B_Timeout1"
   Target_en_us "Bravo to Hammer."
   Modified 1704269526
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464375D9E7B}" {
   Id "AR-RKN_SP01M-VA_FM3B_Timeout2"
   Target_en_us "Enemy has moved on. We missed the opportunity. End of mission. Out."
   Modified 1704269532
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644871FD7277}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Hit"
   Target_en_us "Bravo to Hammer, you're on target. Keep hitting them!"
   Modified 1704279325
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644B9652C9FF}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Left"
   Target_en_us "Left by"
   Modified 1704279382
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464486E9AA533}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Over"
   Target_en_us "Over by"
   Modified 1704279336
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644879218C93}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Prefix"
   Target_en_us "Bravo 2 to Hammer. The shell hit "
   Modified 1704279311
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594644B92F180EE}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Right"
   Target_en_us "Right by"
   Modified 1704279388
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946448673C423B}" {
   Id "AR-RKN_SP01M-VA_FM3C_Adj_Short"
   Target_en_us "Short by"
   Modified 1704279349
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464644430E9D2}" {
   Id "AR-RKN_SP01M-VA_FM3C_Miss2"
   Target_en_us "That was no good. They've moved the cargo up the coastline. I can no longer see from here."
   Modified 1704269615
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464642258A4D3}" {
   Id "AR-RKN_SP01M-VA_FM3C_Request1"
   Target_en_us "Bravo to Hammer, come in?"
   Modified 1704269571
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464645E73B0F1}" {
   Id "AR-RKN_SP01M-VA_FM3C_Request2"
   Target_en_us "We were doing patrol along <i>Ore ridge</i> as we spotted some hostiles unloading cargo into a <i>building to our north-north-west</i>, near the coastline."
   Modified 1704481649
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464645A5A5DCC}" {
   Id "AR-RKN_SP01M-VA_FM3C_Request3"
   Target_en_us "I think we need a fire mission. I'll <i>adjust fire</i> from my position. Out."
   Modified 1704394468
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464647F10448D}" {
   Id "AR-RKN_SP01M-VA_FM3C_Success2"
   Target_en_us "Dead on!. Building is burning and hostiles are fleeing to open sea."
   Modified 1704269634
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464647BA2CC71}" {
   Id "AR-RKN_SP01M-VA_FM3C_Success3"
   Target_en_us "HQ will like this. Bravo out."
   Modified 1704269640
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{65946464535F5CCE}" {
   Id "AR-RKN_SP01M-VA_FM3C_Timeout2"
   Target_en_us "You took too long. They've moved the cargo up the coastline. I can no longer see from here."
   Modified 1704269597
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{659464644E4BAD2F}" {
   Id "AR-RKN_SP01M-VA_FM3C_Timeout3"
   Target_en_us "They'll probably unload the supplies elsewhere. I'll let HQ know. Out."
   Modified 1704269605
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6596C0AAC6766D19}" {
   Id "AR-RKN_SP01M-VA_HQ1"
   Target_en_us "Hammer, HQ."
   Modified 1704378730
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6596C0AAE6A5FF9B}" {
   Id "AR-RKN_SP01M-VA_HQ2"
   Target_en_us "We're getting reports of sudden coordinated enemy action all throughout the northern half of the island."
   Modified 1705681576
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6596C0AA1FCF2A6A}" {
   Id "AR-RKN_SP01M-VA_HQ3"
   Target_en_us "Now, I don't whose asshole they came out of, but right now our primary mission is to preserve enough forces for our eventual response."
   Modified 1704378779
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6596C0AA1A4C0728}" {
   Id "AR-RKN_SP01M-VA_HQ4"
   Target_en_us "I know the outpost is not ready. But I hope you at least got that last shipment of shells, because I will direct all firemissions to you."
   Modified 1704378791
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6596C0AA133184CD}" {
   Id "AR-RKN_SP01M-VA_HQ5"
   Target_en_us "Help them with whatever you have on hand. Godspeed. HQ Out."
   Modified 1704378798
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D2445D85A}" {
   Id "AR-RKN_SP01M-VA_Officer1"
   Target_en_us "Whose brilliant idea was it to build an outpost where trucks can't carry?"
   Modified 1704399519
   Author "Rune"
   LastChanged "Rune"
  }
  CustomStringTableItem "{6594645D5992DC2C}" {
   Id "AR-RKN_SP01M-VA_Officer2"
   Target_en_us "Start unloading these shell crates, would you? I gotta go take a leak."
   Modified 1704399561
   Author "Rune"
   LastChanged "Rune"
  }
 }
}